baseURL       = "http://example.org/"
languageCode  = "fr-fr"
title         = "PharmDesign | Optimisez, attirez, fidélisez avec le merchandising"
summarylength = 25

# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name    = "Acceuil"
url     = ""
weight  = 1
[[menu.nav]]
name    = "A propos"
url     = "about"
weight  = 2
[[menu.nav]]
name    = "Projets"
url     = "portfolio"
weight  = 3
[[menu.nav]]
name    = "Blog"
url     = "blog"
weight  = 4
[[menu.nav]]
name    = "Contactez-nous"
url     = "contact"
weight  = 5

# Site Params
[params]
logo = "images/wordLogo.jpg"
logo_footer = "images/letterLogo.jpg"
favicon_icon = "images/favicon.ico"
favicon_shortcut_icon = "images/favicon.png"
custom_stylesheets = []   # [ "scss/my_1.scss", "scss/my_2.scss" ]
dateFormat = "26 FEB 1994"
# Meta data
description = "PharmDesign | Optimisez, attirez, fidélisez avec le merchandising"
author = "PharmDesign"
# Google Analitycs
googleAnalitycsID = "Your ID"
# We're using formspree.io for form handling, paste your formspree url below
fabform  = "https://fabform.io/f/USAg2Jl"

# Contact Form
[params.contactForm]
placeholder_first_name        = "Prénom"
placeholder_last_name         = "Nom"
placeholder_email             = "E-mail"
placeholder_project_type      = "Type de projet"
placeholder_about_the_project = "À propos du projet"
send_message                  = "Envoyer"

[[params.contactForm.projectType]]
value = "gd"
title  = "Graphics Design"
[[params.contactForm.projectType]]
value = "wd"
title  = "Web Design"

# Navbar Action Button
[params.navAction]
status  = true
name    = "Get in touch"
url     = "contact"


# Banner Section
[params.banner]
enable                = true
background_image      = "images/backgrounds/fullLogo.png"
tagline               = "WE WORK HARD, WE PLAY HARD"
primary_button        = "Nos projets"
primary_button_url    = "portfolio"
secondary_button      = "Nous contacter"
secondary_button_url  = "contact"

[params.blog]
read_more             = "read more"

[params.portfolio]
enable    = true
title     = "NOS PROJETS RÉCENTS"
subtitle  = "Nous avons travaillé sur des projets incroyables et nous sommes fiers de les montrer."
view_project = "Voir le projet"
more_works = "Plus de projets"
scroll_down = "Défiler vers le bas"

[params.call_to_action]
enable              = true
background_image    = "images/backgrounds/cta-background.jpg"
title               = "TRAVAILLONS ENSEMBLE"
primary_button      = "Nous contacter"
primary_button_url  = "contact"
secondary_button    = "Voir nos projets"
secondary_button_url = "portfolio"

[params.footer]
params.footer.qr_print = false
# Footer Contact Info
[params.footer.contactInfo]
title   = "Contact Info"
address = "713 Elmwood St.<br>Prior Lake, MN 55372"
phone   = "409-896-1444"
email   = "info@roxo.co"
# Footer Sitemap
[params.footer.sitemap]
title   = "Sitemap"
[[params.footer.sitemap.link]]
name = "About Company"
url  = "about"
[[params.footer.sitemap.link]]
name = "Projects"
url  = "portfolio"
[[params.footer.sitemap.link]]
name = "Blog"
url  = "blog"
[[params.footer.sitemap.link]]
name = "Contact"
url  = "contact"
# Footer Social Media
[params.footer.social]
title   = "Social Media"
[[params.footer.social.link]]
name = "Medium"
url  = "#"
[[params.footer.social.link]]
name = "Behance"
url  = "#"
[[params.footer.social.link]]
name = "Dribbble"
url  = "#"
[[params.footer.social.link]]
name = "Instagram"
url  = "#"
# Footer Service
[params.footer.service]
title       = "We help brands:"
description = "develop design solutions<br>produce valuable cultural content<br>create fresh brand experience"
[params.footer.back_to_top]
description = "I want to <br> visit again"
